name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Restore previous cache of ~/.m2/repository (if any)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 2) Kick off a “go-offline” so all deps get pulled/cached
      - name: Prepare Maven offline cache
        run: mvn dependency:go-offline -B

      # 3) Your real build
      - name: Build & verify
        run: mvn -B clean verify
