name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura JDK 11 ou 17 para Spring Boot
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Instala dependências e compila o código com Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Executa os testes
      - name: Run tests
        run: mvn test

      # Faz o upload dos logs de testes para o repositório
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-classes
